/*
 * DioCfg.h
 *
 *  Created on: Jul 16, 2024
 *      Author: Hp
 */

#ifndef MCAL_DIO_HEADER_DIOCFG_H_
#define MCAL_DIO_HEADER_DIOCFG_H_

#define DIO_u8_PA0_INITIAL_DIRECTION   DIO_u8_INITIAL_OUTPUT
#define DIO_u8_PD2_INITIAL_DIRECTION   DIO_u8_INITIAL_INPUT
#define DIO_u8_PA0_INITIAL_DIRECTION   DIO_u8_OUTPUT_LOW
#define DIO_u8_PD2_INITIAL_DIRECTION   DIO_u8_INPUT_PULLUP

#endif /* MCAL_DIO_HEADER_DIOCFG_H_ */
